# main text of home
name: Yannan Li
bio: A Girl who travels the world eating noodles

# twitter summary info
description: A blog about technology and stuff related

picture: assets/images/picture.jpg

url: https://yannanlics.github.io/

# if you don't have any of social below, comment the line
email: yannanli@usc.edu

gems:
  - jekyll-seo-tag

exclude: [README.md, Gemfile, Gemfile.lock, _site, Rakefile, travis.sh, vendor]
